[default]
rpc_url = "https://rpc.testnet.miden.io"
rpc_timeout_ms = 10000
client_count = 100
public_account_ids = "0x63c9d7af451fda2000fa06ce0bdefd"
port = 8001
debug = true
[default.db]
url = "notes.db"
